config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'mycourses'=> 'mycourses#index'
  
  resources :courses do
    resources :assignments
  end
  post 'subscribe_course'=> 'courses#subscribe'
  root 'courses#index', as: 'home'
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :groups
	has_many :assignments
	has_many :usercourseactions
  	has_many :users, :through => :usercourseactions
	validates :course_name, presence: true,
						length: {minimum: 8}

# 	def activate  // just for example
#     self.update(activated: true)
#   end
#   def deactivate
#     self.update(activated: false)
#   end


end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	before_action :authenticate_user!, except: [:index]
	def index
		@courses=Course.all
		@courses_user=Course.joins(usercourseactions: :user,usercourseactions: :course)
		@usercourseactions=Usercourseaction.joins(:user, :course)
		
	end

	def new 
		@course =Course.new
		@user=User.find(current_user.id)
	end

	def show
		@course=Course.find(params[:id])
		@user=User.find(current_user.id)
	end

	def create
		#render plain: params[:course].inspect // just for show 

		course = Course.new(course_params)
 		course.users << User.find(current_user.id)
 		
		if(course.save)
			if (!current_user.instructor_id.nil?)
			course.usercourseactions.update(status: 'Create')
			
		else
			course.usercourseactions.update(status: 'Subscribe')
		end
			redirect_to course
		else
			render 'new'
		end	
	end

	def subscribe
		course = Course.find(params[:format])
		course.users << User.find(current_user.id)
		if(course.save)
			if (!current_user.instructor_id.nil?)
			course.usercourseactions.update(status: 'Create')
			else
			course.usercourseactions.update(status: 'Subscribe')
			end
			redirect_to home_path
		else
			redirect_to home_path
		end
	end

	def update 
		@course = Course.find(params[:id])

		if(@course.update(course_params))
			redirect_to @course
		else
			render 'edit'
		end
	end

	def destroy
		@course = Course.find(params[:id])
		authorize @course #pundit
		@course.destroy #pundit
		redirect_to courses_path
	end

	rescue_from Pundit::NotAuthorizedError, with: :user_not_allow
	private def user_not_allow
		flash[:warning] = "You are not allow to delete this course"
		redirect_to home_path
	end

	def edit
			@course = Course.find(params[:id])
	end

	private def course_params
		params.require(:course).permit(:course_name,:course_description)
	end

	private def course_sub_params
		params.require(:course).permit(:course_name,:course_description)
	end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= form_for :course, url: course_path(@course), method: :patch do |c| %>
	<% if @course.errors.any? %>
		<% @course.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		<%= c.label :course_name %><br>
		<%= c.text_field(:course_name, {:class => 'form-control'})%>
	</p>
	<p>
		<%= c.label :course_description %><br>
		<%= c.text_field(:course_description, {:class=> 'form-control'}) %>
	</p>

	<p>
		<%= c.submit({:class=> 'btn btn-primary'})%>
	</p>
	<% end %>

app/views/courses/index.html.erb
<h1>All courses</h1>
<% @courses_user.each do |course| %>
	<div class="card bg-light" style="margin-bottom: 10px" >
	<h3><%= course.course_name %></h3>
	<p><%= course.course_description %></p>
		<p>Instructor ID : <%= course.user_ids %>
			
	<center><div style="width:300px ;margin-bottom: 10px" >
	<%= link_to "Read More", course_path(course), :class => 'btn btn-outline-light btn-secondary'  %>
</div></center>
	</div>
<% end %>
 

app/views/courses/new.html.erb
<h1>Create Course</h1>
<%= form_for :course, url: courses_path do |c| %>
	<% if @course.errors.any? %>
		<% @course.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	<p>
		<%= c.label :course_name %><br>
		<%= c.text_field(:course_name, {:class => 'form-control'})%>
	</p>
	<p>
		<%= c.label :course_description %><br>
		<%= c.text_field(:course_description, {:class=> 'form-control'}) %>
	</p>

	<p>
		<%= c.submit({:class=> 'btn btn-primary'})%>
	</p>
	<% end %>

app/views/courses/show.html.erb
<br/>
<h3><%= @course.course_name %></h3>
<p><%= @course.course_description %></p>
<hr>

<% if current_user.instructor_id.nil? %>
        <%
=begin%>
 <%= button_to "Subscribe",subscribe_course_path(@course), data: {confirm:" Do you want to subscribe this Course ?"}, :class => 'btn btn-primary' %> 
<%
=end%>
        <%= form_for :course, url: subscribe_course_path(@course), method: :post do |c| %>
	
		<% c.text_field(:course_name, {:class => 'form-control',disabled: true,hidden: true})%>
	
		<% c.text_field(:course_description, {:class=> 'form-control',disabled: true,hidden: true}) %>

		<%= c.submit("Subscribe",{:class=> 'btn btn-primary'} )%>
<% end %>
        <% else %>
<%= link_to "Edit",edit_course_path(@course), :class => 'btn btn-primary' %>
<%= link_to "Delete",course_path(@course),method: :delete,data: {confirm: 'Are your sure?'} ,:class => 'btn btn-danger' %>
<% end %>