config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get 'mycourses'=> 'mycourses#index'
  
  resources :courses do
    resources :assignments
  end
  post 'subscribe_course'=> 'courses#subscribe'
  root 'courses#index', as: 'home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningHub</title>
  
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head> 

  <body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
  <a class="navbar-brand" <%= link_to "LearningHub", home_path %> </a>
  <button class="navbar-toggler">
    <span class="navbar-toggler-icon"></span>
  </button>
>
  <div class="collapse navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <a class="nav-link" <%= link_to "Home", home_path %> </a>

      <% if current_user %>
        <% if !current_user.instructor_id.nil? %>  
        <a class="nav-link" <%= link_to " Create Course", new_course_path %> </a>
        <% end %>
                    <a class="nav-link" <%= link_to 'My Course',mycourses_path %> </a>
                    <a class="nav-link" <%= link_to 'Edit Profile', edit_user_registration_path %> </a>
                    <a class="nav-link" <%= link_to 'Logout', destroy_user_session_path, method: :delete %> </a>
                    <a class="nav-link align-right">Welcome, <%= current_user.user_name %> </a>
        <% else %>
                    <a class="nav-link" <%= link_to 'Login ', new_user_session_path %> </a>
                    <a class="nav-link" <%= link_to 'Sign Up', new_user_registration_path %> </a>

        <% end %>

    </ul>
    
  </div>
</nav>
      <div ><%= notice %></div>
       <div><%= alert %></div>
      <div id="flash">
      <% flash.each do |key,value|%>
      <div class="alert alert-<%= key  %>"> <%= value %></div>
      <% end %>
      </div>
<div class="container">
    <%= yield %>
      
    </div>
  </body>
</html>